# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ib7Ftx3_BygCRESGyIYoHOMCle1saAeZ
"""

'''pip install ultralytics==8.3.15 opencv-python pandas numpy shapely tqdm -q
print(" Dependencies installed!")'''

from google.colab import drive
drive.mount('/content/drive')
print("Google Drive mounted!")

from ultralytics import YOLO
import cv2
import pandas as pd
import numpy as np
from tqdm import tqdm
import torch
import os
from shapely.geometry import Point, Polygon
from pathlib import Path

print(" Libraries imported!")

# ============================================
# CONFIGURATION
# ============================================

VIDEO_PATH = '/content/drive/MyDrive/trafficnet_dataset_v1/854745-hd_1280_720_50fps.mp4'
MODEL = 'yolov8s.pt'
OUTPUT_CSV = 'lane_vehicles.csv'
OUTPUT_FRAMES_DIR = 'extracted_frames'
CONF_THRESHOLD = 0.25

# Frame extraction
EXTRACT_FRAMES = True
EXTRACT_EVERY_N_FRAMES = 1  # Extract every frame (1 = all, 30 = every 30th)

VEHICLE_CLASSES = ['car', 'truck', 'bus', 'motorcycle', 'bicycle']

# ============================================
# LANE DEFINITION - UPDATE THESE!
# ============================================
# Video is 1920x1080 - update coordinates based on your video
LANES = {
    'lane_1': {
        'name': 'Lane 1',
        'polygon': [[300, 1080], [500, 500], [650, 500], [500, 1080]]
    },
    'lane_2': {
        'name': 'Lane 2',
        'polygon': [[650, 1080], [800, 500], [950, 500], [800, 1080]]
    },
    'lane_3': {
        'name': 'Lane 3',
        'polygon': [[950, 1080], [1100, 500], [1250, 500], [1100, 1080]]
    }
}

print(" Configuration loaded!")
print(f"   Video: {Path(VIDEO_PATH).name}")
print(f"   Number of lanes: {len(LANES)}")
print(f"   Extract frames: {EXTRACT_FRAMES}")

# Convert lane polygons to Shapely polygons
lane_polygons = {}
for lane_id, lane_info in LANES.items():
    lane_polygons[lane_id] = {
        'polygon': Polygon(lane_info['polygon']),
        'name': lane_info['name'],
        'poly_points': np.array(lane_info['polygon'], dtype=np.int32)
    }

def assign_vehicle_to_lane(center_x, center_y, lanes_dict):
    """Check which lane a vehicle center point belongs to"""
    point = Point(center_x, center_y)
    for lane_id, lane_data in lanes_dict.items():
        if lane_data['polygon'].contains(point):
            return lane_id
    return None

# Create frames directory
if EXTRACT_FRAMES:
    os.makedirs(OUTPUT_FRAMES_DIR, exist_ok=True)

print("Lane polygons initialized!")
print(f"   Total lanes: {len(lane_polygons)}")
if EXTRACT_FRAMES:
    print(f"   Frames directory: {OUTPUT_FRAMES_DIR}")

print("🔍 Verifying video file...")

if not os.path.exists(VIDEO_PATH):
    raise FileNotFoundError(f"Video not found: {VIDEO_PATH}")

cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    raise ValueError(f"Cannot open video: {VIDEO_PATH}")

fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
cap.release()

print(f" Video verified!")
print(f"   Resolution: {width}x{height}")
print(f"   FPS: {fps:.2f}")
print(f"   Total frames: {total_frames}")
print(f"   Duration: {total_frames/fps:.1f} seconds")

print("🚀 Loading YOLOv8 model...")
model = YOLO(MODEL)
vehicle_class_ids = [i for i, name in model.names.items() if name in VEHICLE_CLASSES]

print(f" Model loaded!")
print(f"   Tracking: {VEHICLE_CLASSES}")
print(f"   GPU: {torch.cuda.is_available()}")

print("\n🔄 Processing video...")
print(f"   Counting vehicles in {len(LANES)} lanes per frame\n")

cap = cv2.VideoCapture(VIDEO_PATH)
all_results = []
frame_idx = 0
frames_extracted = 0

pbar = tqdm(total=total_frames, desc="Processing", unit="frame")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Extract frame if needed
    if EXTRACT_FRAMES and (frame_idx % EXTRACT_EVERY_N_FRAMES == 0):
        frame_filename = f"frame_{frame_idx:06d}.jpg"
        frame_path = os.path.join(OUTPUT_FRAMES_DIR, frame_filename)
        cv2.imwrite(frame_path, frame)
        frames_extracted += 1

    # Run YOLO inference
    results = model.predict(
        source=frame,
        conf=CONF_THRESHOLD,
        device=0 if torch.cuda.is_available() else 'cpu',
        verbose=False,
        classes=vehicle_class_ids
    )

    # Initialize frame result
    frame_result = {
        'frame': frame_idx,
        'timestamp': frame_idx / fps,
        'num_lanes': len(LANES)
    }

    # Add frame filename if extracted
    if EXTRACT_FRAMES and (frame_idx % EXTRACT_EVERY_N_FRAMES == 0):
        frame_result['frame_file'] = frame_filename
    else:
        frame_result['frame_file'] = None

    # Initialize vehicle count for each lane
    for lane_id in LANES.keys():
        frame_result[f'{lane_id}_vehicles'] = 0

    # Process detections
    if results and len(results) > 0:
        det = results[0]
        if det.boxes is not None and len(det.boxes) > 0:
            for box in det.boxes:
                xyxy = box.xyxy[0].cpu().numpy()
                x1, y1, x2, y2 = map(int, xyxy)

                # Calculate center point
                center_x = (x1 + x2) / 2.0
                center_y = (y1 + y2) / 2.0

                cls_id = int(box.cls[0].item())
                cls_name = model.names[cls_id]

                # Only count vehicles
                if cls_name in VEHICLE_CLASSES:
                    # Assign to lane
                    assigned_lane = assign_vehicle_to_lane(center_x, center_y, lane_polygons)

                    if assigned_lane:
                        frame_result[f'{assigned_lane}_vehicles'] += 1

    all_results.append(frame_result)
    frame_idx += 1
    pbar.update(1)

pbar.close()
cap.release()

print(f"\n Processing complete!")
print(f"   Processed {len(all_results)} frames")
if EXTRACT_FRAMES:
    print(f"   Extracted {frames_extracted} frames")

print("Saving results...")

# Create DataFrame
df = pd.DataFrame(all_results)

# Rename columns for cleaner output
column_mapping = {}
for lane_id in LANES.keys():
    column_mapping[f'{lane_id}_vehicles'] = f'{LANES[lane_id]["name"]} Vehicles'
df = df.rename(columns=column_mapping)

# Save to CSV
df.to_csv(OUTPUT_CSV, index=False)

print(f" Saved to: {OUTPUT_CSV}")
print(f"\n" + "="*70)
print("RESULTS SUMMARY")
print("="*70)

print(f"\n Overall Statistics:")
print(f"   Total frames processed: {len(df)}")
print(f"   Number of lanes: {df['num_lanes'].iloc[0]}")
if EXTRACT_FRAMES:
    extracted_count = df['frame_file'].notna().sum()
    print(f"   Frames extracted: {extracted_count}")

print(f"\n Vehicles per Lane:")
for lane_id in LANES.keys():
    lane_name = LANES[lane_id]['name']
    col_name = f'{lane_name} Vehicles'
    if col_name in df.columns:
        avg = df[col_name].mean()
        max_count = df[col_name].max()
        total = df[col_name].sum()
        print(f"   {lane_name}:")
        print(f"      Average: {avg:.2f} vehicles/frame")
        print(f"      Maximum: {max_count} vehicles")
        print(f"      Total: {total} vehicles")

print(f"\n Sample Output (first 10 frames):")
display_cols = ['frame', 'timestamp', 'num_lanes']
for lane_id in LANES.keys():
    display_cols.append(f'{LANES[lane_id]["name"]} Vehicles')

print(df[display_cols].head(10).to_string(index=False))

print(f"\n CSV Output Columns:")
print(f"   - frame: Frame number")
print(f"   - timestamp: Time in seconds")
print(f"   - num_lanes: Number of lanes ({df['num_lanes'].iloc[0]})")
for lane_id in LANES.keys():
    print(f"   - {LANES[lane_id]['name']} Vehicles: Vehicle count in this lane")
if EXTRACT_FRAMES:
    print(f"   - frame_file: Filename of extracted frame")

print("\n Done!")

import os
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm
from ultralytics import YOLO

# ============================================
# CONFIGURATION
# ============================================
VIDEO_PATH = '/content/drive/MyDrive/trafficnet_dataset_v1/854745-hd_1280_720_50fps.mp4'
MODEL = 'yolov8s.pt'
OUTPUT_CSV = 'lane_vehicles.csv'
OUTPUT_FRAMES_DIR = 'extracted_frames'
CONF_THRESHOLD = 0.25

# Frame extraction
EXTRACT_FRAMES = True
EXTRACT_EVERY_N_FRAMES = 1  # Extract every frame (1 = all, 30 = every 30th)

VEHICLE_CLASSES = ['car', 'truck', 'bus', 'motorcycle', 'bicycle']

# If polygons were drawn for a reference resolution, set it here for auto-scaling
REFERENCE_WIDTH = 1920
REFERENCE_HEIGHT = 1080

# ============================================
# LANE DEFINITION (reference coordinates)
# ============================================
LANES = {
    'lane_1': {
        'name': 'Lane 1',
        'polygon': [[300, 1080], [500, 500], [650, 500], [500, 1080]]
    },
    'lane_2': {
        'name': 'Lane 2',
        'polygon': [[650, 1080], [800, 500], [950, 500], [800, 1080]]
    },
    'lane_3': {
        'name': 'Lane 3',
        'polygon': [[950, 1080], [1100, 500], [1250, 500], [1100, 1080]]
    }
}

def ensure_dir(path: str) -> None:
    if path and not os.path.exists(path):
        os.makedirs(path, exist_ok=True)

def scale_polygon(points, sx: float, sy: float):
    pts = np.asarray(points, dtype=np.float32)
    pts[:, 0] *= sx
    pts[:, 1] *= sy
    return pts.astype(np.int32)

def build_lane_polygons(lanes_dict, sx: float, sy: float):
    lane_polys = {}
    for lane_id, lane_info in lanes_dict.items():
        poly = scale_polygon(lane_info['polygon'], sx, sy)
        # pointPolygonTest expects Nx1x2 or Nx2 int32; we’ll keep Nx2 and reshape when needed
        lane_polys[lane_id] = poly
    return lane_polys

def assign_vehicle_to_lane(cx: float, cy: float, lane_polygons: dict):
    point = (float(cx), float(cy))
    # Return the first lane that contains the point
    for lane_id, poly in lane_polygons.items():
        # pointPolygonTest expects shape (N,1,2)
        poly_reshaped = poly.reshape((-1, 1, 2))
        res = cv2.pointPolygonTest(poly_reshaped, point, False)
        if res >= 0:  # inside or on edge
            return lane_id
    return None

print("Configuration loaded!")
print(f"  Video: {Path(VIDEO_PATH).name}")
print(f"  Number of lanes: {len(LANES)}")
print(f"  Extract frames: {EXTRACT_FRAMES}")

print("🔍 Verifying video file...")
if not os.path.exists(VIDEO_PATH):
    raise FileNotFoundError(f"Video not found: {VIDEO_PATH}")

cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    raise ValueError(f"Cannot open video: {VIDEO_PATH}")

fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
cap.release()

print("Video verified!")
print(f"  Resolution: {width}x{height}")
print(f"  FPS: {fps:.2f}")
print(f"  Total frames: {total_frames}")
print(f"  Duration: {total_frames/fps:.1f} seconds")

# Auto-scale lane polygons from reference resolution to actual video size
sx = width / float(REFERENCE_WIDTH)
sy = height / float(REFERENCE_HEIGHT)
lane_polygons = build_lane_polygons(LANES, sx, sy)

# (Optional) Create frame output dir
if EXTRACT_FRAMES:
    ensure_dir(OUTPUT_FRAMES_DIR)

print("🚀 Loading YOLOv8 model...")
model = YOLO(MODEL)

# model.names can be list or dict depending on version
if isinstance(model.names, dict):
    id_to_name = model.names
else:
    id_to_name = {i: n for i, n in enumerate(model.names)}

vehicle_class_ids = [i for i, name in id_to_name.items() if name in VEHICLE_CLASSES]

print("Model loaded!")
print(f"  Tracking classes: {VEHICLE_CLASSES}")
print(f"  GPU: {torch.cuda.is_available()}")

print("\n🔄 Processing video...")
print(f"  Counting vehicles in {len(LANES)} lanes per frame\n")

cap = cv2.VideoCapture(VIDEO_PATH)
all_results = []
frame_idx = 0
frames_extracted = 0
pbar = tqdm(total=total_frames, desc="Processing", unit="frame")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Extract frame if needed
    frame_filename = None
    if EXTRACT_FRAMES and (frame_idx % EXTRACT_EVERY_N_FRAMES == 0):
        frame_filename = f"frame_{frame_idx:06d}.jpg"
        frame_path = os.path.join(OUTPUT_FRAMES_DIR, frame_filename)
        cv2.imwrite(frame_path, frame)
        frames_extracted += 1

    # Run YOLO inference
    results = model.predict(
        source=frame,
        conf=CONF_THRESHOLD,
        device=0 if torch.cuda.is_available() else 'cpu',
        verbose=False,
        classes=vehicle_class_ids  # filter to vehicle classes only
    )

    # Initialize frame result
    frame_result = {
        'frame': frame_idx,
        'timestamp': frame_idx / fps,
        'num_lanes': len(LANES),
        'frame_file': frame_filename
    }

    # Initialize vehicle count for each lane
    for lane_id in LANES.keys():
        frame_result[f'{lane_id}_vehicles'] = 0

    # Process detections
    if results and len(results) > 0:
        det = results[0]
        if det.boxes is not None and len(det.boxes) > 0:
            # Convert once for speed
            boxes_xyxy = det.boxes.xyxy.cpu().numpy()
            classes = det.boxes.cls.cpu().numpy().astype(int)
            # Iterate per detection
            for (x1, y1, x2, y2), cls_id in zip(boxes_xyxy, classes):
                # center point of bbox
                center_x = (x1 + x2) * 0.5
                center_y = (y1 + y2) * 0.5

                cls_name = id_to_name.get(cls_id, None)
                if cls_name in VEHICLE_CLASSES:
                    assigned_lane = assign_vehicle_to_lane(center_x, center_y, lane_polygons)
                    if assigned_lane:
                        frame_result[f'{assigned_lane}_vehicles'] += 1

    all_results.append(frame_result)
    frame_idx += 1
    pbar.update(1)

pbar.close()
cap.release()

print("\nProcessing complete!")
print(f"  Processed {len(all_results)} frames")
if EXTRACT_FRAMES:
    print(f"  Extracted {frames_extracted} frames")

print("Saving results...")

# Create DataFrame
df = pd.DataFrame(all_results)

# Rename columns for cleaner output
column_mapping = {}
for lane_id in LANES.keys():
    column_mapping[f'{lane_id}_vehicles'] = f'{LANES[lane_id]["name"]} Vehicles'
df = df.rename(columns=column_mapping)

# Save to CSV
df.to_csv(OUTPUT_CSV, index=False)
print(f"  Saved to: {OUTPUT_CSV}")

print("\n" + "="*70)
print("RESULTS SUMMARY")
print("="*70)
print("\nOverall Statistics:")
print(f"  Total frames processed: {len(df)}")
print(f"  Number of lanes: {df['num_lanes'].iloc[0]}")
if EXTRACT_FRAMES:
    extracted_count = df['frame_file'].notna().sum()
    print(f"  Frames extracted: {extracted_count}")

print("\nVehicles per Lane:")
for lane_id in LANES.keys():
    lane_name = LANES[lane_id]['name']
    col_name = f'{lane_name} Vehicles'
    if col_name in df.columns:
        avg = df[col_name].mean()
        max_count = df[col_name].max()
        total = df[col_name].sum()
        print(f"  {lane_name}:")
        print(f"     Average: {avg:.2f} vehicles/frame")
        print(f"     Maximum: {max_count} vehicles")
        print(f"     Total: {total} vehicles")

print("\nSample Output (first 10 frames):")
display_cols = ['frame', 'timestamp', 'num_lanes']
for lane_id in LANES.keys():
    display_cols.append(f'{LANES[lane_id]["name"]} Vehicles')
print(df[display_cols].head(10).to_string(index=False))

print("\nCSV Output Columns:")
print("  - frame: Frame number")
print("  - timestamp: Time in seconds")
print(f"  - num_lanes: Number of lanes ({df['num_lanes'].iloc[0]})")
for lane_id in LANES.keys():
    print(f"  - {LANES[lane_id]['name']} Vehicles: Vehicle count in this lane")
if EXTRACT_FRAMES:
    print("  - frame_file: Filename of extracted frame")

print("\nDone!")

import os
from pathlib import Path

import cv2
import numpy as np
import torch
from ultralytics import YOLO

# ==========================
# CONFIG
# ==========================
IMAGE_PATH = "/content/drive/MyDrive/trafficnet_dataset_v1/test/dense_traffic/images.jpg"
MODEL = "yolov8s.pt"
CONF_THRESHOLD = 0.25
VEHICLE_CLASSES = ["car", "truck", "bus", "motorcycle", "bicycle"]

# Lane polygon vertical extent: lanes will be built between y_top..y_bottom
# Set y_top near horizon (smaller ratio = closer to top)
HORIZON_Y_RATIO = 0.55  # 0..1
# Hough + merging params
CANNY_LOW = 80
CANNY_HIGH = 200
HOUGH_THRESH = 80
HOUGH_MIN_LINE_LEN = 80
HOUGH_MAX_LINE_GAP = 30
# Consider only "mostly vertical" lane-like lines
MIN_ABS_SLOPE = 0.4
# Merge lines whose x at bottom is within this many pixels
MERGE_X_TOL = 40

def load_image(image_path: str):
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Image not found: {image_path}")
    img = cv2.imread(image_path)
    if img is None:
        raise ValueError(f"Failed to read image: {image_path}")
    return img

def detect_lane_boundaries(image: np.ndarray,
                           canny_low: int,
                           canny_high: int,
                           hough_thresh: int,
                           min_line_len: int,
                           max_line_gap: int,
                           min_abs_slope: float,
                           merge_x_tol: int):
    h, w = image.shape[:2]
    # Edge detection
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 1.2)
    edges = cv2.Canny(blur, canny_low, canny_high)

    # Hough line segments
    lines = cv2.HoughLinesP(
        edges,
        rho=1,
        theta=np.pi / 180.0,
        threshold=hough_thresh,
        minLineLength=min_line_len,
        maxLineGap=max_line_gap
    )

    if lines is None:
        return []

    # Collect candidate lane boundaries as (m, b) in y = m x + b form
    boundaries = []
    for l in lines[:, 0, :]:
        x1, y1, x2, y2 = map(float, l)
        # Avoid division by zero; keep "vertical-ish" lines by slope in x->y space
        dx = (x2 - x1)
        dy = (y2 - y1)
        if abs(dx) < 1e-3:
            # Treat as a very steep line; approximate slope by large value
            m = 1e6 if dy >= 0 else -1e6
        else:
            m = dy / dx
        if abs(m) < min_abs_slope:
            continue
        # Convert to y = m x + b
        b = y1 - m * x1
        boundaries.append((m, b))

    if not boundaries:
        return []

    # Project each boundary to bottom y = h-1; use x_bottom to cluster/merge
    y_bottom = h - 1

    def x_at_y(m, b, y):
        # y = m x + b => x = (y - b)/m
        # Handle extremely steep lines by clamping
        if abs(m) < 1e-6:
            return np.inf
        return (y - b) / m

    # Sort by x at bottom
    boundaries = sorted(boundaries, key=lambda mb: x_at_y(mb[0], mb[1], y_bottom))

    # Merge boundaries with similar x_bottom
    merged = []
    current_group = []
    prev_x = None
    for m, b in boundaries:
        xb = x_at_y(m, b, y_bottom)
        if prev_x is None or abs(xb - prev_x) <= merge_x_tol:
            current_group.append((m, b))
        else:
            merged.append(current_group)
            current_group = [(m, b)]
        prev_x = xb
    if current_group:
        merged.append(current_group)

    # Average each group to a single boundary
    merged_boundaries = []
    for group in merged:
        ms = np.array([g[0] for g in group], dtype=np.float64)
        bs = np.array([g[1] for g in group], dtype=np.float64)
        m_avg = float(np.median(ms))
        b_avg = float(np.median(bs))
        merged_boundaries.append((m_avg, b_avg))

    # Sort final boundaries by x_bottom ascending
    merged_boundaries.sort(key=lambda mb: x_at_y(mb[0], mb[1], y_bottom))
    return merged_boundaries

def build_lane_polygons_from_boundaries(boundaries, img_width: int, img_height: int, horizon_ratio: float):
    """
    Build quadrilateral polygons between adjacent boundaries.
    Each boundary is a line y = m x + b. We take y_top..y_bottom and compute x on each boundary.
    """
    y_top = int(max(0, min(img_height - 1, img_height * horizon_ratio)))
    y_bottom = img_height - 1

    def x_at_y(m, b, y):
        if abs(m) < 1e-6:
            return np.inf
        return (y - b) / m

    # If < 2 boundaries, treat whole image width as one lane
    if len(boundaries) < 2:
        lane_poly = np.array([
            [0, y_bottom],
            [0, y_top],
            [img_width - 1, y_top],
            [img_width - 1, y_bottom]
        ], dtype=np.int32)
        return [lane_poly]

    # Build vertical boundary strips
    xs_bottom = [x_at_y(m, b, y_bottom) for (m, b) in boundaries]
    xs_top = [x_at_y(m, b, y_top) for (m, b) in boundaries]

    # Clip to image range to avoid infs
    def clip_x(x):
        if not np.isfinite(x):
            return 0
        return int(np.clip(round(x), 0, img_width - 1))

    xs_bottom = list(map(clip_x, xs_bottom))
    xs_top = list(map(clip_x, xs_top))

    lane_polys = []
    for i in range(len(boundaries) - 1):
        xlb = xs_bottom[i]
        xub = xs_bottom[i + 1]
        xlt = xs_top[i]
        xut = xs_top[i + 1]

        # Ensure left <= right
        left_b = min(xlb, xub)
        right_b = max(xlb, xub)
        left_t = min(xlt, xut)
        right_t = max(xlt, xut)

        # Discard degenerate lanes
        if right_b - left_b < 5 and right_t - left_t < 5:
            continue

        poly = np.array([
            [left_b,  y_bottom],
            [left_t,  y_top],
            [right_t, y_top],
            [right_b, y_bottom]
        ], dtype=np.int32)
        lane_polys.append(poly)

    # If merging produced no valid polygons, fallback to single lane
    if not lane_polys:
        lane_poly = np.array([
            [0, y_bottom],
            [0, y_top],
            [img_width - 1, y_top],
            [img_width - 1, y_bottom]
        ], dtype=np.int32)
        lane_polys = [lane_poly]

    return lane_polys

def count_vehicles_per_lane(image_bgr: np.ndarray,
                            model: YOLO,
                            vehicle_class_ids: list[int],
                            conf_threshold: float,
                            lane_polygons: list[np.ndarray]):
    # Inference
    results = model.predict(
        source=image_bgr,
        conf=conf_threshold,
        device=0 if torch.cuda.is_available() else 'cpu',
        verbose=False,
        classes=vehicle_class_ids
    )

    h, w = image_bgr.shape[:2]
    # Initialize counts
    lane_counts = [0 for _ in lane_polygons]

    if results and len(results) > 0:
        det = results[0]
        if det.boxes is not None and len(det.boxes) > 0:
            boxes = det.boxes.xyxy.cpu().numpy()
            for (x1, y1, x2, y2) in boxes:
                cx = 0.5 * (x1 + x2)
                cy = 0.5 * (y1 + y2)
                # Check which lane polygon contains the center
                for idx, poly in enumerate(lane_polygons):
                    # pointPolygonTest expects (N,1,2)
                    res = cv2.pointPolygonTest(poly.reshape((-1, 1, 2)), (float(cx), float(cy)), False)
                    if res >= 0:
                        lane_counts[idx] += 1
                        break

    return lane_counts

def main():
    print("Loading image...")
    img = load_image(IMAGE_PATH)
    h, w = img.shape[:2]
    print(f"  Image size: {w}x{h}")

    print("Detecting lane boundaries...")
    boundaries = detect_lane_boundaries(
        img,
        CANNY_LOW,
        CANNY_HIGH,
        HOUGH_THRESH,
        HOUGH_MIN_LINE_LEN,
        HOUGH_MAX_LINE_GAP,
        MIN_ABS_SLOPE,
        MERGE_X_TOL
    )

    lane_polys = build_lane_polygons_from_boundaries(
        boundaries,
        img_width=w,
        img_height=h,
        horizon_ratio=HORIZON_Y_RATIO
    )
    num_lanes = len(lane_polys)
    print(f"  Estimated lanes: {num_lanes}")

    print("Loading YOLO model...")
    model = YOLO(MODEL)

    # Normalize names mapping across versions
    if isinstance(model.names, dict):
        id_to_name = model.names
    else:
        id_to_name = {i: n for i, n in enumerate(model.names)}
    vehicle_class_ids = [i for i, name in id_to_name.items() if name in VEHICLE_CLASSES]
    print(f"  Vehicle class IDs: {vehicle_class_ids}")

    print("Counting vehicles per lane...")
    counts = count_vehicles_per_lane(
        image_bgr=img,
        model=model,
        vehicle_class_ids=vehicle_class_ids,
        conf_threshold=CONF_THRESHOLD,
        lane_polygons=lane_polys
    )

    # Report
    print("\nRESULT")
    print(f"Number of lanes: {num_lanes}")
    for i, c in enumerate(counts, start=1):
        print(f"  Lane {i}: {c} vehicles")

    # Optional visualization
    vis = img.copy()
    # draw lane polygons
    for i, poly in enumerate(lane_polys, start=1):
        cv2.polylines(vis, [poly], isClosed=True, color=(0, 255, 0), thickness=2)
        # label
        M = cv2.moments(poly)
        if abs(M["m00"]) > 1e-6:
            cx = int(M["m10"] / M["m00"])
            cy = int(M["m01"] / M["m00"])
            cv2.putText(vis, f"Lane {i}", (cx - 30, cy), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2, cv2.LINE_AA)

    out_path = str(Path(IMAGE_PATH).with_name("lanes_vehicles_vis.jpg"))
    cv2.imwrite(out_path, vis)
    print(f"\nSaved visualization: {out_path}")

if __name__ == "__main__":
    main()

